packages:
  darwin:
    taps:
    - tw93/tap
    brews:
    - bat
    - fd
    - fzf
    - gh
    - mole
    - neovim
    - node
    - ripgrep
    - zoxide

    casks:
    - cc-switch
    - claude-code
    - clash-verge-rev
    - dbeaver-community
    - docker-desktop
    - font-fira-code-nerd-font
    - font-maple-mono-nf-cn
    - google-chrome
    - obsidian
    - postman
    - sublime-text
    - visual-studio-code
    - yuanbao
